title: Saum
description: Luxury Pilgrimages
url: "https://www.saum.in"
baseurl: ""

# Build settings
markdown: kramdown

# Exclude files from Jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - RathYatraItinerary.pdf